---
apiVersion: v1
kind: Pod
metadata:
  name: reis-pod
  labels:
    type: db
spec:
  containers:
    - name: myredis
      image: redis
      volumeMounts:
        - mountPath: /data/redis
          name: myredis
  volumes:
    - name: myredis
      emptyDir: {}
...