---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  namespace: test-ns
  labels:
    type: cms
spec:
  containers:
    - name: myghost
      image: ghost
      ports:
        - containerPort: 2368
          hostPort: 8080
      env:
        - name: NODE_ENV
          value: development
...