---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    auther: sai
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    auther: sai
    type: proxy
...
