---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    auther: sai
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    auther: sai
    type: ci-cd
...
